Update times

diff --git a/times b/times
--- a/times
+++ b/times
@@ -1,233 +1,233 @@
-#! / bin / bash
+#!/bin/bash
 
-# _ ___ _ _ _ ____ _____ _ _ ______ __ ____ ___ _____ 
-# | | / / | El | El | \ | | / ___ | El | ___ | El | El | El | _ \ \ / / _ / ___ | _ _ | _ _ |
-# | '/ | El | El | El | \ | El | El | _ | | _ | El | El | El | | _) \ V / _ | | _ | El | _ | El | El | El |  
-# | . \ | | _ | El | | \ | | _ | El | El | _ | El | | _ | El | _ <| El | | _ _ | El | | _ | || El | El | El |  
-# | _ | \ _ \\ ___ / | _ | \ _ | \ ____ | | _ | \ ___ / | _ | \ _ \ | _ | | _ | \ ____ | ___ | | _ |  
-# #                                                                                                                        
-# Un script bash en el tema de Kung Fury, utilizando git --date para cometer 
-# en el pasado. Efectivamente hackeándote en el tiempo.
+#  _  ___   _ _   _  ____   _____ _   _ ______   __           ____ ___ _____ 
+# | |/ / | | | \ | |/ ___| |  ___| | | |  _ \ \ / /    _     / ___|_ _|_   _|
+# | ' /| | | |  \| | |  _  | |_  | | | | |_) \ V /   _| |_  | |  _ | |  | |  
+# | . \| |_| | |\  | |_| | |  _| | |_| |  _ < | |   |_   _| | |_| || |  | |  
+# |_|\_\\___/|_| \_|\____| |_|    \___/|_| \_\|_|     |_|    \____|___| |_|  
+#                                                                                                                        
+# A bash script in the theme of Kung Fury, utilizing git --date to commit 
+# in the past. Effectivly hacking you back in time.
 
-# Las confirmaciones de Git se realizan una vez al día al lanzar monedas al azar psuedo de la
-# fecha de inicio elegida. Simplemente ejecute esto nuevamente si su densidad de confirmación deseada es
-# menos de lo deseado.
+# Git commits are done on a once per-day psuedo-random coin flip basis from the
+# chosen start date. Simply run this again if your desired commit density is
+# less than desired.
 
-# Mire esto para obtener referencias de películas GUI: https://youtu.be/bS5P_LAqiVg?t=9m52s
+# Watch this to get GUI movie References: https://youtu.be/bS5P_LAqiVg?t=9m52s
 
-# Autor: William Golembieski
-# Correo electrónico: BillGolembieski@projectu23.com
+# Author: William Golembieski
+# Email: BillGolembieski@projectu23.com
 
-################################################## #############################
+###############################################################################
 
-# Quería ver cuántas veces se ejecuta esto. Google Analytics simple.
-export analytics_id = "UA-89577187-1"
-categoría de exportación = "AppCounter"
-export action = "CountAction"
-etiqueta de exportación = "CountLabel"
-valor de exportación = "1"
+# Wanted to see how many times this is run. Simple google analytics.
+export analytics_id="UA-89577187-1"
+export category="AppCounter"
+export action="CountAction"
+export label="CountLabel"
+export value="1"
 
 curl -s -X POST \
-        -d 'v = 1 & tid =' "$ analytics_id" '& cid = 555 & t = event & ec =' "$ category" \
-        '& ea =' "$ action" '& el =' "$ label" '& ev =' "$ value" '' \
+        -d 'v=1&tid='"$analytics_id"'&cid=555&t=event&ec='"$category"\
+        '&ea='"$action"'&el='"$label"'&ev='"$value"'' \
         -H "User-Agent: AppSpecific" \
-        https://www.google-analytics.com/collect> / dev / null &
+        https://www.google-analytics.com/collect > /dev/null &
         
-################################################## #############################
+###############################################################################
 
-# Comprobar si el usuario es root
-si ["$ EUID" -ne 0]; luego
-	echo "Por favor, ejecuta como root. Prueba sudo bash timehack"
-	salida
+# Check if user is root
+if [ "$EUID" -ne 0 ]; then
+	echo "Please run as root. Try sudo bash timehack"
+	exit
 fi
 
-################################################## #############################
+###############################################################################
 
-# Obtener OS
-plataforma de exportación = 'desconocido'
-export system_name = `uname`
-if [["$ system_name" == 'Linux']]; luego
-	plataforma = 'linux'
-elif [["$ system_name" == 'Darwin']]; luego
-	plataforma = 'osx'
+# Get OS
+export platform='unknown'
+export system_name=`uname`
+if [[ "$system_name" == 'Linux' ]]; then
+	platform='linux'
+elif [[ "$system_name" == 'Darwin' ]]; then
+	platform='osx'
 fi
 
-################################################## #############################
+###############################################################################
 
-# Carga completa
-cuadro de diálogo --backtitle "GitHub Time Hacker" --infobox "LOAD COMPLETE". 3 20
-dormir 1.25
+# Load Complete
+dialog --backtitle "GitHub Time Hacker" --infobox "LOAD COMPLETE." 3 20
+sleep 1.25
 
-################################################## #############################
+###############################################################################
 
-# Inicializando secuencia de pirateo
-export hacker_github_name = ""
-exportar hacker_email = ""
+# Initializing Hack Sequence
+export hacker_github_name=""
+export hacker_email=""
 
-exec 3> & 1
+exec 3>&1
 
-diálogo --separate-widget $ '\ n' --ok-label "Enviar" \
+dialog --separate-widget $'\n' --ok-label "Submit" \
 	--backtitle "GitHub Time Hacker" \
-	- título "INICIALIZANDO LA SECUENCIA DE HACK"
-	--form "\ nIntroduzca la información de GitHub: \ nUtilice flechas o haga clic para mover" \
+	--title "INITIALIZING HACK SEQUENCE" \
+	--form "\nEnter GitHub information:\nUse arrows or click to move" \
 	12 50 0 \
-	"Nombre de usuario:" 1 1 "$ hacker_github_name" 1 10 20 0 \
-	"Correo electrónico:" 2 1 "$ hacker_email" 2 10 40 0 ​​\
-2> & 1 1> & 3 | {
-	leer -r hacker_github_name
-	leer -r hacker_email
-	código de salida = $?
+	"Username:" 1 1 "$hacker_github_name" 1 10 20 0 \
+	"Email:" 2 1 "$hacker_email" 2 10 40 0 \
+2>&1 1>&3 |{
+	read -r hacker_github_name
+	read -r hacker_email
+	exitcode=$?
 
-	if ["$ exitcode" = 0]; luego
-		git config - global credential.helper cache
-		git config - global credential.helper 'cache --timeout = 600'
-		git config --global user.email "$ hacker_email"
-		git config --global user.name "$ hacker_github_name"
+	if [ "$exitcode" = 0 ]; then
+		git config --global credential.helper cache
+		git config --global credential.helper 'cache --timeout=600'
+		git config --global user.email "$hacker_email"
+		git config --global user.name "$hacker_github_name"
 		git config --global push.default simple
 
-	más
-		eco
-		echo "Abortado"
-		salida
+	else
+		echo
+		echo "Aborted"
+		exit
 	fi
 }
-exec 3> & -
+exec 3>&-
     
-################################################## #############################
+###############################################################################
 
 # Initalizing Time Portal Screens
-cuadro de diálogo --backtitle "GitHub Time Hacker" \
-	--infobox "INICIALIZANDO EL PORTAL DE TIEMPO". 3 31
-dormir .9
+dialog --backtitle "GitHub Time Hacker" \
+	--infobox "INITIALIZING TIME PORTAL." 3 31
+sleep .9
 
-cuadro de diálogo --backtitle "GitHub Time Hacker" \
-	--infobox "PORTAL DE INICIALIZACIÓN DEL TIEMPO .." 3 31
-dormir .9
+dialog --backtitle "GitHub Time Hacker" \
+	--infobox "INITIALIZING TIME PORTAL.." 3 31
+sleep .9
 
-cuadro de diálogo --backtitle "GitHub Time Hacker" \
-	--infobox "INICIALIZANDO EL PORTAL DEL TIEMPO ..." 3 31
-dormir .9
+dialog --backtitle "GitHub Time Hacker" \
+	--infobox "INITIALIZING TIME PORTAL..." 3 31
+sleep .9
 
-################################################## #############################
+###############################################################################
 
-# Entrada de calendario
-date_picked = $ (dialog --stdout --title "TIME PORTAL" \
+# Calender input
+date_picked=$(dialog --stdout --title "TIME PORTAL" \
 		--backtitle "GitHub Time Hacker" \
 		--no-cancel \
-		--date-format '% Y% m% d' \
-		--calendar "\ nSeleccione una fecha para hackear \ nback a tiempo para:" \
+		--date-format '%Y%m%d' \
+		--calendar "\nSelect a date to hack\nback in time to:" \
 		0 0)
                  
-if ["$ date_picked"! = ""]; luego
+if [ "$date_picked" != "" ]; then
 
-    if ["$ platform" = "linux"]; luego
-		d1 = $ (fecha -d "00:00" +% s)
-		d2 = $ (date -d $ date_picked +% s)
-	elif ["$ plataforma" = "osx"]; luego
-		d1 = $ (fecha -j -f "% a% b% d% T% Z% Y" "` fecha` "" +% s ")
-		d2 = $ (fecha -j -f "% Y% m% d" "$ date_picked" "+% s")
-	más
-		d1 = $ (fecha -d "00:00" +% s)
-		d2 = $ (date -d $ date_picked +% s)
+    if [ "$platform" = "linux" ]; then
+		d1=$(date -d "00:00" +%s)
+		d2=$(date -d $date_picked +%s)
+	elif [ "$platform" = "osx" ]; then
+		d1=$(date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s")
+		d2=$(date -j -f "%Y%m%d" "$date_picked" "+%s")
+	else
+		d1=$(date -d "00:00" +%s)
+		d2=$(date -d $date_picked +%s)
 	fi
 	
-	days_diff = $ ((($ d1- $ d2) / 86400))
+	days_diff=$(( ($d1-$d2) / 86400 ))
 
-más
-    eco
-    echo "Abortado"
-	salida
+else
+    echo
+    echo "Aborted"
+	exit
 fi
 
-################################################## #############################
+###############################################################################
 
-# Comprometerse
-daysHacked = 0
-hasta ["$ daysHacked" -eq "$ days_diff"]
-hacer
-	FLIP = $ (($ RANDOM% 10))
+# Committing
+daysHacked=0
+until [ "$daysHacked" -eq "$days_diff" ]
+do
+	FLIP=$(($RANDOM%10))
 	
-	si [$ FLIP -ge 2]; luego
-		if ["$ platform" = "linux"]; luego
-    	d = $ (date -d "$ date_picked + $ daysHacked days" +% b ""% d "00:00"% Y)
+	if [ $FLIP -ge 2 ]; then
+		if [ "$platform" = "linux" ]; then
+    	d=$(date -d "$date_picked + $daysHacked days" +%b" "%d" 00:00 "%Y)
 
-		elif ["$ plataforma" = "osx"]; luego
-	d = $ (fecha -j -f "% a% b% d% T% Z% Y" "` fecha -v + "$ días Hackeado" "d" `" \
-	"+% ​​b% d 00:00% Y")
+		elif [ "$platform" = "osx" ]; then
+	d=$(date -j -f "%a %b %d %T %Z %Y" "`date -v +"$daysHacked""d"`" \
+	"+%b %d 00:00 %Y")
 
-		más
-	d = $ (date -d "$ date_picked + $ daysHacked days" +% b ""% d "00:00"% Y)
+		else
+	d=$(date -d "$date_picked + $daysHacked days" +%b" "%d" 00:00 "%Y)
 	fi
-	git commit --quiet --allow-empty --date = "$ d" -m "Tiempo pirateado"
+	git commit --quiet --allow-empty --date="$d" -m "Hacked Time"
 	
-	si [$ FLIP -ge 4]; luego
-	git commit --quiet --allow-empty --date = "$ d" -m "Tiempo pirateado 2x"
-	git commit --quiet --allow-empty --date = "$ d" -m "Tiempo pirateado 2x"
+	if [ $FLIP -ge 4 ]; then 
+	git commit --quiet --allow-empty --date="$d" -m "Hacked Time 2x"
+	git commit --quiet --allow-empty --date="$d" -m "Hacked Time 2x"
 	
-			si [$ FLIP -ge 8]; luego
-	git commit --quiet --allow-empty --date = "$ d" -m "Tiempo pirateado 3x"
-	git commit --quiet --allow-empty --date = "$ d" -m "Tiempo pirateado 3x"
-	git commit --quiet --allow-empty --date = "$ d" -m "Tiempo pirateado 3x"
+			if [ $FLIP -ge 8 ]; then
+	git commit --quiet --allow-empty --date="$d" -m "Hacked Time 3x"
+	git commit --quiet --allow-empty --date="$d" -m "Hacked Time 3x"
+	git commit --quiet --allow-empty --date="$d" -m "Hacked Time 3x"
 	
-				si [$ FLIP = 9]; luego
-	git commit --quiet --allow-empty --date = "$ d" -m "Tiempo pirateado 4x"
-	git commit --quiet --allow-empty --date = "$ d" -m "Tiempo pirateado 4x"
+				if [ $FLIP = 9 ]; then 
+	git commit --quiet --allow-empty --date="$d" -m "Hacked Time 4x"
+	git commit --quiet --allow-empty --date="$d" -m "Hacked Time 4x"
 
 				fi
 			fi
 		fi
 	fi
-((daysHacked ++))
-hecho
+((daysHacked++))
+done
 
-################################################## #############################
+###############################################################################
 
-# E = Convertidor mc2
-COUNT = 10
+# E = mc2 Converter
+COUNT=10
 (
-mientras prueba $ COUNT! = 110
-hacer
-	echo $ COUNT
+while test $COUNT != 110
+do
+	echo $COUNT
 	echo "XXX"
-	echo "ALGORITMOS DE CONVERSIÓN EN MARCHA"
+	echo "CONVERSION ALGORITHMS RUNNING"
 	echo "XXX"
-	COUNT = `expr $ COUNT + 10`
-	dormir .5
-hecho
-) | cuadro de diálogo --título "E = mc2 CONVERTER" --gauge "" 8 70 0
+	COUNT=`expr $COUNT + 10`
+	sleep .5
+done
+) | dialog --title "E = mc2 CONVERTER" --gauge "" 8 70 0
 
-################################################## #############################
+###############################################################################
 
-# E = mensaje mc3
-cuadro de diálogo --backtitle "GitHub Time Hacker" \
+# E = mc3 message
+dialog --backtitle "GitHub Time Hacker" \
 	--infobox "E = mc3" 3 31
-dormir .9
+sleep .9
 
-cuadro de diálogo --backtitle "GitHub Time Hacker" \
-	--infobox "" 3 31
-dormir .9
+dialog --backtitle "GitHub Time Hacker" \
+	--infobox " " 3 31
+sleep .9
 
-cuadro de diálogo --backtitle "GitHub Time Hacker" \
+dialog --backtitle "GitHub Time Hacker" \
 	--infobox "E = mc3" 3 31
-dormir .9
+sleep .9
 
-cuadro de diálogo --backtitle "GitHub Time Hacker" \
-	--infobox "" 3 31
-dormir .9
-cuadro de diálogo --backtitle "GitHub Time Hacker" \
+dialog --backtitle "GitHub Time Hacker" \
+	--infobox " " 3 31
+sleep .9
+dialog --backtitle "GitHub Time Hacker" \
 	--infobox "E = mc3" 3 31
-dormir .9
+sleep .9
 
-################################################## #############################
+###############################################################################
 
-# Estás a punto de hackear el tiempo, ¿estás seguro?
-cuadro de diálogo --backtitle "GitHub Time Hacker" \
-	- título "ADVERTENCIA" \
-	--sino "\ n ¿ESTÁS ACERCA DE \ nHACK HACK, \ n ¿ESTÁS SEGURO?" 10 30
+# You are about to hack time are you sure?
+dialog --backtitle "GitHub Time Hacker" \
+	--title "WARNING" \
+	--yesno "\nYOU'RE ABOUT\nTO HACK TIME,\nARE YOU SURE?" 10 30
        
-yn_response = $?
-caso $ yn_response en
-	0) empuje git ;;
-	1) echo "Abortado";
-	255) echo "Abortado";
+yn_response=$?
+case $yn_response in
+	0) git push;;
+	1) echo "Aborted";;
+	255) echo "Aborted";;
 esac
